### PR TITLE
rewrite!!!!!!

### PR DESCRIPTION
**Pull request by notiriscent**
fully redesigned (nerd lynith moment) and rewritten variant!!!!

what do you think @TheKodeToad

### CODE REVIEW

**Review by TheKodeToad — CHANGES_REQUESTED** [review]
Thank you! Just a few things (as usual)... I'm such a critic I know.

SolClient should be two words (that was changed very early), and the icons probably should be white.

I think it may look better if the logo was separated from the background.
Here it is (from eyezah):


For Server Integration
> Mods to integrate with Hypixel and potentially other servers in future!

is what I intended it to be. Although that is maybe a bit honest but I can't help it.

There's also a gap in the centre which I feel something could go it.

No pressure to fix these things! If you don't I can try myself (that will go well won't it).

**Comment by notiriscent** [comment]
Fixed the majority of requested things, except for:
> There's also a gap in the centre which I feel something could go it.

1. what gap :sob:
2. what could go in it

**Comment by TheKodeToad** [comment]
[](https://imgur.com/PzkVlNl.png)
this gap.

Either just change the layout back, or put "Features" or something.

Also I think the logo should be smaller like it was before, just on top of the parallax.

**Comment by notiriscent** [comment]
> [](https://imgur.com/PzkVlNl.png) this gap.
> 
> Either just change the layout back, or put "Features" or something.
> 
> Also I think the logo should be smaller like it was before, just on top of the parallax.

gotcha, will try to fix rn

**Comment by notiriscent** [comment]
how bout dis???

**Comment by TheKodeToad** [comment]
Looking better! Maybe the logo should be above the text like before though.

There's also the GitHub and 'cord buttons.

**Comment by notiriscent** [comment]
> Looking better! Maybe the logo should be above the text like before though.
> 
> There's also the GitHub and 'cord buttons.

so im thinking, how about the orange "Sol Client" text is in the logo (the sun) and the description + buttons are below it?
sounds junky but might work out

**Comment by TheKodeToad** [comment]
It's not part of the logo so I don't think that will work.

**Comment by notiriscent** [comment]
> It's not part of the logo so I don't think that will work.

so should i just bring back the buttons layout from the previous PR?

**Comment by TheKodeToad** [comment]
> > It's not part of the logo so I don't think that will work.
> 
> so should i just bring back the buttons layout from the previous PR?

I think that would look better.

**Comment by notiriscent** [comment]
> > > It's not part of the logo so I don't think that will work.
> > 
> > 
> > so should i just bring back the buttons layout from the previous PR?
> 
> I think that would look better.

aight, working on it

**Comment by TheKodeToad** [comment]
Thanks!

**Comment by notiriscent** [comment]
hoaw abouat diss???

**Comment by TheKodeToad** [comment]
I will just get it to how I want it later. I think I liked the buttons in the corner.

**Comment by notiriscent** [comment]
ok toad

**Comment by RaptaG** [comment]
How can I preview the site?

**Comment by notiriscent** [comment]
> How can I preview the site?

pretty broken but you can at [my fork](https://github.com/FelixFromDiscord/sol-web-rewrite/tree/rewrite)

**Comment by notiriscent** [comment]
closed because old 👴

**Comment by TheKodeToad** [comment]
Fair enough, others were working on a design!

**Comment by TheKodeToad** [comment]
image
(this is meant as a joke, don't take it personally!)

**Pull request closed without merging**
